import { LegalScreen } from '../../src/components/LegalScreen';
import { appLocale } from '../../src/i18n';

const ES = {
  title: 'TÉRMINOS',
  updated: '29 de junio de 2026',
  sections: [
    {
      h: '1. Quién opera la app y aceptación',
      b: 'El Sargento es operado por Jhonatan Villagómez ("nosotros"), de forma individual. Al usar la app aceptas estos términos. Si no estás de acuerdo, no la uses. Contacto: jhonatanvillagomez38@gmail.com.',
    },
    {
      h: '2. Qué es la app',
      b: 'El Sargento es un coach de productividad de ENTRETENIMIENTO con personajes ficticios. NO es terapia, ni consejo médico, legal, financiero ni profesional de ningún tipo. Las respuestas las genera una IA y pueden contener errores.',
    },
    {
      h: '3. Tono de los personajes',
      b: 'Los sargentos usan humor exigente y "regañón" como recurso motivacional. No representa ofensas reales hacia ti. Si en algún momento no te sienta bien, deja de usar la app.',
    },
    {
      h: '4. Tu cuenta',
      b: 'Eres responsable de mantener segura tu contraseña y de la actividad de tu cuenta. Debes dar información veraz al registrarte y tener al menos 13 años (o la edad mínima legal en tu país).',
    },
    {
      h: '5. Suscripción, prueba y renovación',
      b: 'La app ofrece una prueba gratuita de 7 días y, después, una suscripción de pago con RENOVACIÓN AUTOMÁTICA. Se cobra a través de tu cuenta de App Store (Apple) o Google Play. Puedes cancelar en cualquier momento desde los ajustes de tu tienda; la cancelación detiene futuras renovaciones y conservas el acceso hasta el fin del periodo ya pagado.',
    },
    {
      h: '6. Reembolsos',
      b: 'Como regla general NO ofrecemos reembolsos por periodos ya cobrados ni por tiempo no utilizado. Sin embargo, los reembolsos los procesa y decide la tienda (App Store / Google Play) conforme a sus políticas, y respetamos cualquier reembolso que la ley aplicable de tu país te otorgue de forma obligatoria. Para solicitarlos, dirígete a la tienda donde compraste.',
    },
    {
      h: '7. Uso aceptable',
      b: 'No uses la app para fines ilícitos, ni intentes vulnerar su seguridad, abusar de la IA o de la infraestructura.',
    },
    {
      h: '8. Disponibilidad',
      b: 'Hacemos lo posible por mantener la app funcionando, pero puede haber interrupciones o cambios. La función de IA depende de servicios de terceros.',
    },
    {
      h: '9. Limitación de responsabilidad',
      b: 'La app se ofrece "tal cual" y "según disponibilidad". En la medida máxima permitida por la ley, no somos responsables de daños indirectos o derivados del uso, ni de las decisiones que tomes basándote en la app.',
    },
    {
      h: '10. Emergencias',
      b: 'Si vives una crisis o emergencia, contacta a servicios profesionales o líneas de ayuda de tu país. Esta app no sustituye atención profesional.',
    },
    {
      h: '11. Ley aplicable',
      b: 'La app se distribuye internacionalmente a través de App Store y Google Play. Estos términos se interpretan conforme a la legislación aplicable según tu país de residencia, sin que ello te prive de los derechos imperativos que la ley de tu jurisdicción te reconozca como consumidor.',
    },
    {
      h: '12. Cambios y contacto',
      b: 'Podemos actualizar estos términos; publicaremos la nueva versión aquí con su fecha. Dudas: jhonatanvillagomez38@gmail.com.',
    },
  ],
};

const EN = {
  title: 'TERMS',
  updated: 'June 29, 2026',
  sections: [
    {
      h: '1. Who operates the app and acceptance',
      b: 'El Sargento is operated by Jhonatan Villagómez ("we"), as an individual. By using the app you accept these terms. If you do not agree, do not use it. Contact: jhonatanvillagomez38@gmail.com.',
    },
    {
      h: '2. What the app is',
      b: 'El Sargento is an ENTERTAINMENT productivity coach with fictional characters. It is NOT therapy, nor medical, legal, financial or professional advice of any kind. Replies are generated by an AI and may contain errors.',
    },
    {
      h: '3. The characters\' tone',
      b: 'The sergeants use demanding, "scolding" humor as a motivational device. It does not represent real offense toward you. If at any point it does not feel right, stop using the app.',
    },
    {
      h: '4. Your account',
      b: 'You are responsible for keeping your password safe and for your account activity. You must provide truthful information when signing up and be at least 13 years old (or the minimum legal age in your country).',
    },
    {
      h: '5. Subscription, trial and renewal',
      b: 'The app offers a 7-day free trial and, after that, a paid subscription with AUTOMATIC RENEWAL. It is billed through your App Store (Apple) or Google Play account. You can cancel anytime from your store settings; cancellation stops future renewals and you keep access until the end of the period already paid.',
    },
    {
      h: '6. Refunds',
      b: 'As a general rule we do NOT offer refunds for periods already billed or for unused time. However, refunds are processed and decided by the store (App Store / Google Play) under its policies, and we honor any refund that the applicable law of your country grants you on a mandatory basis. To request one, go to the store where you purchased.',
    },
    {
      h: '7. Acceptable use',
      b: 'Do not use the app for unlawful purposes, or attempt to breach its security, abuse the AI or the infrastructure.',
    },
    {
      h: '8. Availability',
      b: 'We do our best to keep the app running, but there may be interruptions or changes. The AI feature depends on third-party services.',
    },
    {
      h: '9. Limitation of liability',
      b: 'The app is provided "as is" and "as available". To the maximum extent permitted by law, we are not liable for indirect or consequential damages from use, nor for decisions you make based on the app.',
    },
    {
      h: '10. Emergencies',
      b: 'If you are in a crisis or emergency, contact professional services or helplines in your country. This app does not replace professional care.',
    },
    {
      h: '11. Governing law',
      b: 'The app is distributed internationally through the App Store and Google Play. These terms are interpreted under the law applicable to your country of residence, without depriving you of the mandatory consumer rights granted by the law of your jurisdiction.',
    },
    {
      h: '12. Changes and contact',
      b: 'We may update these terms; we will publish the new version here with its date. Questions: jhonatanvillagomez38@gmail.com.',
    },
  ],
};

export default function TermsScreen() {
  const d = appLocale() === 'en' ? EN : ES;
  return <LegalScreen title={d.title} updated={d.updated} sections={d.sections} />;
}
